server:
  port: 8080

spring:
  application:
    name: ai-master-appeal-service
  datasource:
    url: jdbc:mysql://localhost:3306/ai_master?useUnicode=true&characterEncoding=utf8&useSSL=false&serverTimezone=Asia/Shanghai
    username: root
    password: 123456
    driver-class-name: com.mysql.cj.jdbc.Driver
  
mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.ai.master.appeal.infrastructure.persistence.entity

dubbo:
  application:
    name: ai-master-appeal-service
  registry:
    address: zookeeper://localhost:2181
  protocol:
    name: dubbo
    port: 20880
  scan:
    base-packages: com.ai.master.appeal.service

logging:
  level:
    com.ai.master: debug
    org.mybatis: debug